###
POST http://localhost:3000/api/artistas
Content-Type: application/json

{
    "nombre": "Leonardo Da Vinci",
    "apellidos": "Pintor",
    "fechaCreacion": "2022-01-01T00:00:00.000Z"
}

###
GET http://localhost:3000/api/artistas
