
###
POST  http://localhost:3000/api/obras
Content-Type: application/json

{
    "nombre": "El grito",
    "descripcion": "Pintura",
    "fecha": "2022-01-01",
    "precio": "123456",
    "idartista": "1"
}
###

GET http://localhost:3000/api/obras